---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/argo-homelab.git
      path: kubernetes/apps/longhorn-system/longhorn
      targetRevision: main
      ref: repo
    - repoURL: https://charts.longhorn.io/
      chart: longhorn
      targetRevision: 1.8.0
      helm:
        releaseName: longhorn
        valueFiles:
          - $repo/kubernetes/apps/longhorn-system/longhorn/values.yaml
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
