---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argo-system
spec:
  project: default
  source:
    repoURL: https://github.com/tholinka/homelab.git
    path: kubernetes/argo/settings
    targetRevision: main
  destination:
    name: in-cluster
    namespace: argo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy
