---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/homelab.git
      path: kubernetes/apps/cert-manager/cert-manager
      targetRevision: main
      ref: repo
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.3
      helm:
        releaseName: cert-manager
        valueFiles:
          - $repo/kubernetes/apps/cert-manager/cert-manager/values.yaml
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
