apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 1
  type: ReplicaSet
  version: '7.0.16'
  security:
    authentication:
      modes:
        - 'SCRAM'
        - 'SCRAM-SHA-1'
  users:
    - name: unifi
      db: unifi
      passwordSecretRef:
        name: unifi-mongo
        key: password
      roles:
        - name: dbOwner
          db: unifi
        - name: dbOwner
          db: unifi_stat
      scramCredentialsSecretName: unifi-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ['ReadWriteOnce']
            storageClassName: longhorn-large
            resources:
              requests:
                storage: 5G
        - metadata:
            name: logs-volume
          spec:
            accessModes: ['ReadWriteOnce']
            storageClassName: longhorn-replicated
            resources:
              requests:
                storage: 2G
