apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-mongo
spec:
  refreshInterval: '15s'
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: unifi-mongo
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: unifi
