---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-community-operator
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mongo
    name: in-cluster
  project: default
  sources:
    - chart: community-operator
      repoURL: 'https://mongodb.github.io/helm-charts'
      targetRevision: 0.12.0
    - repoURL: https://github.com/tholinka/argo-homelab.git
      path: kubernetes/apps/mongo/mongo
      targetRevision: main
      ref: repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
