---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubernetes
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
