kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-large
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: '1'
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ''
  fsType: 'ext4'
  backupTargetName: 'none'
  #mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
  diskSelector: 'large'
  nodeSelector: 'storage,large'
  recurringJobSelector: '[]'
