kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: '1' # 1 for now until the other nodes get setup
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ''
  fsType: 'ext4'
  backupTargetName: 'default'
  #mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
  diskSelector: 'small'
  #nodeSelector: 'storage,small'
  recurringJobSelector: '[{ "name": "snap", "isGroup": true },{ "name": "backup", "isGroup": false }]'
