# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:l0x1+ifJyjECJiBO/1q/Y6vFgUEXxQ==,iv:bwXq7YW30lWBecUxBM7/R10KNV4HDKtFY0RRJWf70hU=,tag:2AJCNndjfngN4J2fh0k9aQ==,type:str]
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:DBr/Apt4wdBQ//zQ0DkgByuvHCdsAA==,iv:HUi6tdJI1OSwA7Ak7rW3r5rWJNW6rs5wcFZHXn54dd4=,tag:048QxHwMykCimpnWWqYudA==,type:str]
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - tholinka.dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQWVESENCdFpKM2wwNFoy
            ODE3N2RkOTd2R1pIYXhWZlpmZHhuM25qS3dJCjkyaGJBb0s2K21LbzJ4QVBZeVdT
            WWtzMjJINm54czk1L2RUaTZLQU1vc3MKLS0tIEgzS1RXN1FIZTV4cnUrVTQzQmpU
            VS9wTnVyRnNCNmg0dURBODc3UHQxQTAKCigPuZ3GWVf+HhCK/g6zs+/t1p8YxKgA
            FVqfpfgm0KU4K1OsF6HrCs8gL8Sj0caGkMFcG5eZ/ZoRrKx8XF/FJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T16:39:25Z"
    mac: ENC[AES256_GCM,data:KGdTV59rQhUAlAkD2cH8X1OixNi4dgkh3AgAWOODWruTb+x1pnEVqLb/9p6r1nDnQP4VcMUZ+iFFolXyDcVXRo03ATW7+T0ShTwgKVHxeeJrZhv2yJJ1UcZZIT9jn5RJwNslmNwwIRxc7OpjyzNGHLWZX7RuOus+8CI4ilBBXHU=,iv:n0ZoLNZ7aV/spMj0WDwlTMCshOYxX7rJL+YdKyJU040=,tag:jxFqve64kr6/7OBmgPwMkg==,type:str]
    pgp: []
    encrypted_regex: ^(email)$
    mac_only_encrypted: true
    version: 3.9.1
