# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:l0x1+ifJyjECJiBO/1q/Y6vFgUEXxQ==,iv:bwXq7YW30lWBecUxBM7/R10KNV4HDKtFY0RRJWf70hU=,tag:2AJCNndjfngN4J2fh0k9aQ==,type:str]
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:DBr/Apt4wdBQ//zQ0DkgByuvHCdsAA==,iv:HUi6tdJI1OSwA7Ak7rW3r5rWJNW6rs5wcFZHXn54dd4=,tag:048QxHwMykCimpnWWqYudA==,type:str]
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - tholinka.dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQWVESENCdFpKM2wwNFoy
            ODE3N2RkOTd2R1pIYXhWZlpmZHhuM25qS3dJCjkyaGJBb0s2K21LbzJ4QVBZeVdT
            WWtzMjJINm54czk1L2RUaTZLQU1vc3MKLS0tIEgzS1RXN1FIZTV4cnUrVTQzQmpU
            VS9wTnVyRnNCNmg0dURBODc3UHQxQTAKCigPuZ3GWVf+HhCK/g6zs+/t1p8YxKgA
            FVqfpfgm0KU4K1OsF6HrCs8gL8Sj0caGkMFcG5eZ/ZoRrKx8XF/FJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T01:07:11Z"
    mac: ENC[AES256_GCM,data:qFqmNe2v2zA+hEnjEXCU6aVBgsisru5bj6IhMnDq9GWNj1naDralL707K/ivSkKVUg/SWHIql4V8pZ5M4LdeuRpN9z2wS+6TwbR4C4lwXXz5UWKqeoDYSZbKO9W7bRzNTop0TU19PKcESgpEpuDG/51sSGZDQzCR8IADpYLQmKg=,iv:RpmNXE4c5AOKZvlIwUcyutr7WHNMysxTBcnTz42ZQ8A=,tag:QM5cLRlezbX/DybV6l8vKQ==,type:str]
    pgp: []
    encrypted_regex: ^(email)$
    mac_only_encrypted: true
    version: 3.9.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: selfsigned-issuer
spec:
    selfSigned: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQWVESENCdFpKM2wwNFoy
            ODE3N2RkOTd2R1pIYXhWZlpmZHhuM25qS3dJCjkyaGJBb0s2K21LbzJ4QVBZeVdT
            WWtzMjJINm54czk1L2RUaTZLQU1vc3MKLS0tIEgzS1RXN1FIZTV4cnUrVTQzQmpU
            VS9wTnVyRnNCNmg0dURBODc3UHQxQTAKCigPuZ3GWVf+HhCK/g6zs+/t1p8YxKgA
            FVqfpfgm0KU4K1OsF6HrCs8gL8Sj0caGkMFcG5eZ/ZoRrKx8XF/FJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T01:07:11Z"
    mac: ENC[AES256_GCM,data:qFqmNe2v2zA+hEnjEXCU6aVBgsisru5bj6IhMnDq9GWNj1naDralL707K/ivSkKVUg/SWHIql4V8pZ5M4LdeuRpN9z2wS+6TwbR4C4lwXXz5UWKqeoDYSZbKO9W7bRzNTop0TU19PKcESgpEpuDG/51sSGZDQzCR8IADpYLQmKg=,iv:RpmNXE4c5AOKZvlIwUcyutr7WHNMysxTBcnTz42ZQ8A=,tag:QM5cLRlezbX/DybV6l8vKQ==,type:str]
    pgp: []
    encrypted_regex: ^(email)$
    mac_only_encrypted: true
    version: 3.9.1
