# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2MV7BO7eqlEzlndKxaIhsNmKW3k7D4HqrJccATpWiLPF8WN9kdbF/g==,iv:Wdk3YrgWsxEd+fjoMlqqwp3SuMDHD29RJp9iQNVJdnM=,tag:IyqNo8/Vr0Y0u9xnATsEWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOHprZXpaQVZuV2VhZlo5
        aWZnaC9sc09LZEZHQVFnbHd6QXZlYTFEM2l3CnFoWDEyMzFkZ3AwUVNNcXRubnlB
        RFJ6V1JLeW90V3J3Z28xUEpBVDNnUTQKLS0tICtPTDNDQTZCeEMzVHNiVGtoZVdU
        SzJYNSt4VklVTW1OZysrNllCNjhKRTQKeoVTmX1PvRH+UmUQP9r79DhfVg5OFNSj
        BJ8SLTyuVqFchejTZzV2WiOYG8Bu/eXRvuWoPAV2d02A11ywsVdOJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-24T02:25:24Z"
  mac: ENC[AES256_GCM,data:lhSx1xeZ8+dhE+7+SO2IZccd8hWh97S2ESIAjRRkAUCocDMEmrs9RZDgs1GKhHDvy1J3zma20ENtVyH5MSPEyDjHDXeSYuaRgSZXwdj4UBODfd/5vZEfzG+erL+iELKE+hoqGnBVamQz2NeP8hzHzYPyQf2+vlcKEECAZbeaJLg=,iv:e6ns7Oqt0agMCPefxFg1ZDbbxKJGVn5krGudaCP+Gfw=,tag:G+tTebMka5AfKA0FoVnlQA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
