---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/argo-homelab.git
      path: kubernetes/apps/network/cloudflared
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/bjw-s/helm
      chart: app-template
      targetRevision: 3.6.1
      helm:
        releaseName: cloudflared
        valueFiles:
          - $repo/kubernetes/apps/network/cloudflared/values.yaml
  destination:
    name: in-cluster
    namespace: network
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
