---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/argo-homelab.git
      path: kubernetes/apps/network/ingress-nginx/certificates
      targetRevision: main
      ref: repo
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.0
      helm:
        releaseName: ingress-nginx-internal
        valueFiles:
          - $repo/kubernetes/apps/network/ingress-nginx/internal/values.yaml
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.0
      helm:
        releaseName: ingress-nginx-external
        valueFiles:
          - $repo/kubernetes/apps/network/ingress-nginx/external/values.yaml
  destination:
    name: in-cluster
    namespace: network
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
