apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/homelab.git
      path: kubernetes/apps/network/kube-vip
      targetRevision: main
      ref: repo
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
  info:
    - name: 'Github Repository:'
      value: >-
        https://github.com/kube-vip/kube-vip
    - name: 'Github releases:'
      value: >-
        https://github.com/kube-vip/kube-vip/releases
    - name: 'Official documentation:'
      value: >-
        https://kube-vip.io/docs/
