apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: external-dns-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.sops.yaml
