---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/argo-homelab.git
      path: kubernetes/apps/observability/kube-prometheus-stack
      targetRevision: main
      ref: repo
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 68.3.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $repo/kubernetes/apps/observability/kube-prometheus-stack/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
