---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/argo-homelab.git
      path: kubernetes/apps/observability/loki
      targetRevision: main
      ref: repo
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.25.0
      helm:
        releaseName: loki
        valueFiles:
          - $repo/kubernetes/apps/observability/loki/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
