---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-smartctl-exporter
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/tholinka/homelab.git
      path: kubernetes/apps/observability/prometheus-smartctl-exporter
      targetRevision: main
      ref: repo
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-smartctl-exporter
      targetRevision: 0.13.0
      helm:
        releaseName: prometheus-smartctl-exporter
        valueFiles:
          - $repo/kubernetes/apps/observability/prometheus-smartctl-exporter/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
