---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/tholinka/homelab.git
      path: kubernetes/apps/unifi
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: unifi
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
