installCRDs: true
image:
  repository: ghcr.io/external-secrets/external-secrets
bitwarden-sdk-server:
  enabled: true
  podAnnotations:
    secret.reloader.stakater.com/reload: 'bitwarden-css-certs,bitwarden-secrets-manager,bitwarden-tls-certs'
certController:
  image:
    repository: ghcr.io/external-secrets/external-secrets
  serviceMonitor:
    enabled: true
    interval: 1m
grafana:
  enabled: true
reportsController:
  serviceMonitor:
    enabled: true
    interval: 1m
serviceMonitor:
  enabled: true
  interval: 1m
webhook:
  image:
    repository: ghcr.io/external-secrets/external-secrets
  serviceMonitor:
    enabled: true
    interval: 1m
