---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    name: in-cluster
  project: kubernetes
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.13.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $repo/kubernetes/apps/external-secrets/values.yaml
    - repoURL: https://github.com/tholinka/argo-homelab
      path: kubernetes/apps/external-secrets
      targetRevision: main
      ref: repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
