loki:
  auth_enabled: false
  analytics:
    reporting_enabled: false
  server:
    log_level: info
  commonConfig:
    replication_factor: 1
  compactor:
    working_directory: /var/loki/compactor/retention
    delete_request_store: filesystem
    retention_enabled: true
  ingester:
    chunk_encoding: snappy
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: '2024-04-01'
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn-large
    size: 50Gi
gateway:
  replicas: 1
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
chunksCache:
  enabled: false
resultsCache:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
