apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:lbpWX3csjjp2K8cCJdS+KJHc+OY8TQH3jJX7ybKej5UAP3i+,iv:vAUWtV4Mw2T6fyovGxAY2XhZ4vdF+/ae8IHy5Xpn+/g=,tag:yqp/UyI6tmS7LIIJO9c/CA==,type:str]
    credentials.json: ENC[AES256_GCM,data:uJzHaCTuuDGJLV59MyEZofJb0CwYNRPvQZAKfWH0s19r3lUweRgzbhABfTlq4XfvHQVjTv8Iswbe4VeAZa5Iu+vdt2jmnIDrcPpN+8k/jw/tBh5hyYL+d8zTsIbNkopC9TzNpCqAzc1TWoKMuSp0DA1XcFlLQsGPPqlEfGPGDTOqqzLUVxQ7zmtZtfnPIK0VxhElhpdzNRlS/nEt57yqF3pMdV2CwlSPKOfkt1aQZCJ/t1I=,iv:QtlU3lhW9o/cLwjVgoYFulvgbnnat9de2TUBKkhmuOw=,tag:OK2wxhBTRwm8vcb0JTKkiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j34t6fwv5evlf9gxchc3x9v6zypufszzuynxycrxk4r4jwxtfq9ss9dmtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YXdZZWoySTdJTjA0eEVi
            Nk5OcXlpbEtHN0pvZFEwUlNxRk9rWThySURnCjcyK21DL09PQStNb0FwR0Z0L2Fu
            b0ZNQXN3bkVFQmNUdG5sQ3RRbWJmQkUKLS0tIGs0eVZpQys1Y3owUythQzhlbFRx
            T0hsTVV5dUsrYUNWVkNNVm5iRFdReVUKMgcdJS0vzA6+AzLWaUc9enNbBueG9ZYG
            ND1Sefcm1bfepAJlVknJl2Hh9C0DXO93U76Tvq914jCclDtEs3Ivzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T15:25:42Z"
    mac: ENC[AES256_GCM,data:lZJBqeT/dTd3yBIZuW777fxDOuGIEeh3LydTTNUHssDSMU1rosH0iNvy1FazIWhHBzIoe+gvelxyfTJVM59oJYa9TaUc+HB+o68h8UKfoKsn7hqRpS1Kzb+uzEPonYoYg3CgQFO79zVrHrrXZkRDNMiEjIWOX1dbuJCkN8b0vV4=,iv:9tIK37FWGxjVaLXWyo44+V3wv/hcDO3aTbWfpRO++mY=,tag:EoHgXIzMnyJIY9KVWL7IfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
