# test an alert: https://gist.github.com/cherti/61ec48deaaab7d288c9fcf17e700853a?permalink_comment_id=3388440#gistcomment-3388440
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name alertmanager-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_wait: 1m
            group_interval: 10m
            repeat_interval: 24h
            receiver: all
            routes:
              - receiver: heartbeat
                group_interval: 5m
                group_wait: 0s
                matchers:
                  - alertname =~ "Watchdog"
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: all
                continue: true
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          receivers:
            - name: heartbeat
            - name: "null"
            - name: all
              discord_configs:
                - webhook_url: "{{ .DISCORD_WEBHOOK }}"
              email_configs:
                - to: "{{ .EMAIL_TO }}"
                  from: "{{ .EMAIL_FROM }}"
                  smarthost: "{{ .EMAIL_HOST }}"
                  auth_username: "{{ .EMAIL_USERNAME }}"
                  auth_identity: "{{ .EMAIL_USERNAME }}"
                  auth_password: "{{ .EMAIL_PASSWORD }}"
  dataFrom:
    - extract:
        key: alertmanager
# example secret in vault:
# {
# 	"DISCORD_WEBHOOK": "https://discord.com/api/webhooks/x/x-x",
# 	"EMAIL_TO": "x@gmail.com",
# 	"EMAIL_FROM": "x+alertmanager@gmail.com",
# 	"EMAIL_HOST": "smtp.gmail.com:587",
# 	"EMAIL_USERNAME": "x@gmail.com",
# 	"EMAIL_PASSWORD": "x"
# }

# default if you don't apply this file

# route:
#   receiver: "null"
#   group_by:
#   - namespace
#   routes:
#   - receiver: "null"
#     matchers:
#     - alertname = "Watchdog"
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 12h
# inhibit_rules:
# - target_matchers:
#   - severity =~ warning|info
#   source_matchers:
#   - severity = critical
#   equal:
#   - namespace
#   - alertname
# - target_matchers:
#   - severity = info
#   source_matchers:
#   - severity = warning
#   equal:
#   - namespace
#   - alertname
# - target_matchers:
#   - severity = info
#   source_matchers:
#   - alertname = InfoInhibitor
#   equal:
#   - namespace
# - target_matchers:
#   - alertname = InfoInhibitor
# receivers:
# - name: "null"
# templates:
# - /etc/alertmanager/config/*.tmpl
