replicas: 1
autoscale:
  enabled: false

persistence:
  type: pvc
  enabled: true
  storageClassName: longhorn-large

ingress:
  enabled: true
  ingressClassName: internal
  hosts:
    - grafana.tholinka.dev

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: loki
        type: loki
        url: http://loki-gateway.observability.svc.cluster.local
      - name: alertmanager
        type: alertmanager
        url: http://mimir-nginx.observability.svc.cluster.local
        jsonData:
          implementation: mimir
          handleGrafanaManagedAlerts: true
      - name: mimir
        type: prometheus
        url: http://mimir-nginx.observability.svc.cluster.local:80/prometheus

sidecar:
  alerts:
    enabled: true
    #searchNamespace: ALL
  dashboards:
    enabled: true
    #searchNamespace: ALL
  datasources:
    enabled: true
    defaultDatasourceEnabled: true
    #searchNamespace: A1LL
  plugins:
    enabled: true
    #searchNamespace: A1LL
  notifiers:
    enabled: true
    #searchNamespace: ALL
