multitenancy_enabled: false

metaMonitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: longhorn-large
  statefulSet:
    enabled: true

compactor:
  persistentVolume:
    size: 20Gi
    storageClass: longhorn-large

ingester:
  persistentVolume:
    size: 50Gi
    storageClass: longhorn-large

store_gateway:
  persistentVolume:
    size: 10Gi
    storageClass: longhorn-large

# we'll use the standalone minio instance
minio:
  enabled: false

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio.minio.svc.cluster.local:9000
          access_key_id: 'mimir'
          secret_access_key: 'supersecretpassword'
          insecure: true
          region: null
    blocks_storage:
      s3:
        bucket_name: mimir-tsdb
    alertmanager_storage:
      s3:
        bucket_name: mimir-ruler
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
